export { default as akshayJoshi } from "./akshay joshi.jpeg";
export { default as anishDe } from "./anish de.jpeg";
export { default as anishKumar } from "./Anish Kumar.jpeg";
export { default as ayanS } from "./Ayan S.jpeg";
export { default as drAnjaniPriyadarshini } from "./Dr. Anjani Priyadarshini.jpeg";
export { default as drJayaprakash } from "./dr_jayaprakash.jpeg";
export { default as gauravPathak } from "./gaurav pathak.jpeg";
export { default as monicaShityalkar } from "./monica shityalkar.jpeg";
export { default as niteshPrasad } from "./nitesh_prasad.jpeg";
export { default as prasadChitt } from "./prasad chitt.jpeg";
export { default as prasantMisra } from "./prasant misra.jpeg";
export { default as rajathKumarS } from "./Rajath_Kumar_S.jpeg";
export { default as rameshNaiduLaveti } from "./rameshnaidulaveti.jpeg";
export { default as sandeshJayarama } from "./Sandesh Jayarama.jpeg";
export { default as shashank1811 } from "./Shashank_1811.jpg";
export { default as shashankN } from "./shashank_n.jpeg";
export { default as sreenivasaRamanujamJ } from "./sreenivasa ramanujam j.jpeg";
export { default as vyshakTm } from "./vyshak tm.jpeg";
export { default as hrishikeshHaritas } from "./hrishikesh_haritas.jpeg";
export { default as vimalBastin } from "./vimal_bastin.jpeg";
export { default as drKunalSaxena } from "./dr_kunal_saxena.jpeg";
export { default as rakshitPrabhakar } from "./rakshit_prabhakar.jpeg";
export { default as drSwetha } from "./dr_swetha.jpeg";
export { default as sourav } from "./sourav.jpeg";
export { default as vellankiSriharsha } from "./vellanki_sriharsha.jpeg";
export { default as vishalRathod } from "./vishal_rathod.jpeg";
